### PR TITLE
Fix bugs and add state persister

### LINKED ISSUE #146: Provide a participant to reenter a room by refreshing the room page
Right now a logged-in participant can reenter a room just by refreshing the room which should not be possible.

### PR DESCRIPTION
**Pull request by FabianAronsson**
Added a caching service to quickly be able to update the room across multiple users. In the future we could look at using Redis instead, but for now this will work.

If we still want to have a permament persister we can create a separate point for that.

Fixes #146 #140

### CODE REVIEW

File: Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs [hunk 1]
```diff
@@ -1,24 +1,42 @@
...
+    {
+        await Groups.AddToGroupAsync(Context.ConnectionId, roomName);
     }
 
-    public Task JoinRoom(string roomName)
+    public async Task<RoomModel> InitializeParticipant(ParticipantRoomDto participant, string roomId, string roomName)
     {
-        return Groups.AddToGroupAsync(Context.ConnectionId, roomName);
+        if (_cacheService.InitRoom(roomId, roomName, participant))
+            await Clients.Groups(roomId).SendAsync("MoveParticipant", participant, Status.Idling);
```
Comment (Mojtabarezaei4) [inline Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs:32]: I assume this line is responsible for adding a new participant to either of the lists of the room. But this will be hit only once, only the first time.

File: Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs [hunk 2]
```diff
@@ -1,24 +1,42 @@
...
+        await Clients.Groups(roomId).SendAsync("MoveParticipant", participantToBeUpdated, status);
+    }
+
+    public async Task JoinRoom(string roomName)
+    {
+        await Groups.AddToGroupAsync(Context.ConnectionId, roomName);
     }
 
-    public Task JoinRoom(string roomName)
+    public async Task<RoomModel> InitializeParticipant(ParticipantRoomDto participant, string roomId, string roomName)
```
Comment (Mojtabarezaei4) [inline Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs:29]: If this line is responsible for adding a new participant to either of the lists of the room then it should update the cache too when the not first participant enters.

**Review by Mojtabarezaei4 — CHANGES_REQUESTED** [review]

File: Queueomatic/Server/Services/CacheRoomService/CacheRoomService.cs [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+        private readonly IMemoryCache _cache;
+        public CacheRoomService(IMemoryCache cache)
+        {
+            _cache = cache ?? throw new ArgumentException($"The value of cache cannot be null");
+        }
+
+        public RoomModel GetRoom(string roomId) => (RoomModel)_cache.Get(roomId);
+        
+
+        public bool InitRoom(string roomId, string roomName, ParticipantRoomDto participant)
```
[the remark this answers is not in the document]
Comment (FabianAronsson) [reply Queueomatic/Server/Services/CacheRoomService/CacheRoomService.cs]: Changed in new commit.

File: Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs (hunk 1 above)
Comment (FabianAronsson) [reply Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs]: Yes, and this was incorrect. Changed in new commit.

File: Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs (hunk 2 above)
Comment (FabianAronsson) [reply Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs:29]: It should and it is now changed to do that.
